22 membuat view list dan delete modul transkrip nilai
jacky-htg/tugas-project-web-2 pull request #41
Opened 2023-07-16 05:32 UTC by TheodoreVK

2023-07-16 07:10 UTC, jacky-htg requested changes
mas @TheodoreVK tolong 
1. file view delete dihapus
2. untuk list sementara saya accept dulu, tapi nanti kalau api list sdh jadi ganti datatable call api ya mas.

2023-07-16 07:10 UTC, jacky-htg commented on app/Views/delete_transkrip_nilai.php
> +<?= $this->extend('layouts/main'); ?>
ini dihapus saja mas, untuk delete tidak memerlukan view

2023-07-16 07:10 UTC, jacky-htg commented on app/Views/delete_transkrip_nilai.php
> +<?= $this->extend('layouts/main'); ?>
maksdunya file ii dihapus saja

2023-07-16 07:10 UTC, jacky-htg commented
untuk sementara halaman list boleh seperti ini ya mas, tapi nanti kalau api sudah jadi, diganti dengan call api. thanks

2023-07-16 07:24 UTC, jacky-htg requested changes
minimal buatkan routing untuk delete dengan method post

2023-07-16 07:29 UTC, jacky-htg commented on app/Views/list_transkrip_nilai.php
> +                        <a href="<?php echo $deleteUrl; ?>" class="btn btn-danger" onclick="return confirm('Apakah Anda yakin ingin menghapus?')">Delete</a>
untuk button delete dibuat form saja, 
```
<form method="post" action="<?php echo $deleteUrl;?>"
<button type="submit">Delete</button>
</form>
```

2023-07-16 13:14 UTC, TheodoreVK commented on app/Views/list_transkrip_nilai.php
> +                        <a href="<?php echo $deleteUrl; ?>" class="btn btn-danger" onclick="return confirm('Apakah Anda yakin ingin menghapus?')">Delete</a>
oke, sorry mas masih belajar jd belum paham antara method get sama post

2023-07-17 06:44 UTC, jacky-htg submitted a review, later dismissed

2023-07-17 06:49 UTC, merged